# Generated by Django 3.1.3 on 2020-11-10 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0002_auto_20201110_1134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='djangousers',
            name='name',
        ),
        migrations.AddField(
            model_name='djangousers',
            name='email',
            field=models.CharField(default='NA', max_length=255),
        ),
        migrations.AddField(
            model_name='djangousers',
            name='firstName',
            field=models.CharField(default='NA', max_length=255),
        ),
        migrations.AddField(
            model_name='djangousers',
            name='lastName',
            field=models.CharField(default='NA', max_length=255),
        ),
        migrations.AddField(
            model_name='djangousers',
            name='loginName',
            field=models.CharField(default='NA', max_length=255),
        ),
    ]
