# Generated by Django 3.1.3 on 2020-11-10 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0003_auto_20201110_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='djangousers',
            name='userType',
            field=models.CharField(default='NA', max_length=255),
        ),
    ]
