# Generated by Django 3.1.3 on 2020-11-10 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0005_biodiversityrecords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biodiversityrecords',
            name='userType',
            field=models.TextField(),
        ),
    ]
