# Generated by Django 3.1.3 on 2020-11-10 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0006_auto_20201110_1426'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='biodiversityrecords',
            name='email',
        ),
        migrations.RemoveField(
            model_name='biodiversityrecords',
            name='firstName',
        ),
        migrations.RemoveField(
            model_name='biodiversityrecords',
            name='lastName',
        ),
        migrations.RemoveField(
            model_name='biodiversityrecords',
            name='loginName',
        ),
        migrations.RemoveField(
            model_name='biodiversityrecords',
            name='userType',
        ),
        migrations.AddField(
            model_name='biodiversityrecords',
            name='acceptedSpeciesName',
            field=models.TextField(default='NA'),
        ),
        migrations.AddField(
            model_name='biodiversityrecords',
            name='speciesName',
            field=models.TextField(default='NA'),
        ),
    ]
