# Generated by Django 3.1.3 on 2020-11-10 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0008_auto_20201110_1446'),
    ]

    operations = [
        migrations.CreateModel(
            name='speciesRecords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speciesName', models.CharField(default='NA', max_length=255)),
                ('acceptedSpeciesName', models.CharField(default='NA', max_length=255)),
            ],
            options={
                'verbose_name_plural': 'species',
            },
        ),
        migrations.DeleteModel(
            name='djangousers',
        ),
    ]
