# Generated by Django 3.1.3 on 2020-11-10 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0009_auto_20201110_1544'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='biodiversityrecords',
            name='acceptedSpeciesName',
        ),
        migrations.RemoveField(
            model_name='biodiversityrecords',
            name='speciesName',
        ),
        migrations.AddField(
            model_name='biodiversityrecords',
            name='Class',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='biodiversityrecords',
            name='Family',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='biodiversityrecords',
            name='Genus',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='biodiversityrecords',
            name='Kingdom',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='biodiversityrecords',
            name='Order',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='biodiversityrecords',
            name='Phylum',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='biodiversityrecords',
            name='SampleCollector',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='biodiversityrecords',
            name='SampleConservationMethod',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='biodiversityrecords',
            name='SampleDesign',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='biodiversityrecords',
            name='SampleN',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='biodiversityrecords',
            name='SampleStorageLabel',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='biodiversityrecords',
            name='SampleStorageLocation',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='biodiversityrecords',
            name='SampleType',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='biodiversityrecords',
            name='acceptedNameUsage',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='biodiversityrecords',
            name='acceptedNameUsageID',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='biodiversityrecords',
            name='accessRights',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='biodiversityrecords',
            name='associatedMedia',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='biodiversityrecords',
            name='associatedReferences',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='biodiversityrecords',
            name='associatedSequences',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='biodiversityrecords',
            name='basisOfRecord',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='biodiversityrecords',
            name='behavior',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='biodiversityrecords',
            name='bibliographicCitation',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='biodiversityrecords',
            name='coordinateUncertaintyInMeters',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='biodiversityrecords',
            name='country',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='biodiversityrecords',
            name='dataGeneralizations',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='biodiversityrecords',
            name='datasetName',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='biodiversityrecords',
            name='dateIdentified',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='biodiversityrecords',
            name='day',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='biodiversityrecords',
            name='decimalLatitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='biodiversityrecords',
            name='decimalLongitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='biodiversityrecords',
            name='establishmentMeans',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='biodiversityrecords',
            name='fieldNotes',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='biodiversityrecords',
            name='geodeticDatum',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='biodiversityrecords',
            name='georeferenceProtocol',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='biodiversityrecords',
            name='georeferenceRemarks',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='biodiversityrecords',
            name='identificationRemarks',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='biodiversityrecords',
            name='identificationVerificationStatus',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='biodiversityrecords',
            name='identifiedBy',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='biodiversityrecords',
            name='individualCount',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='biodiversityrecords',
            name='license',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='biodiversityrecords',
            name='lifeStage',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='biodiversityrecords',
            name='locality',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='biodiversityrecords',
            name='location',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='biodiversityrecords',
            name='materialSample',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='biodiversityrecords',
            name='materialSampleID',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='biodiversityrecords',
            name='maximumDepthInMeters',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='biodiversityrecords',
            name='measurementAccuracy',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='biodiversityrecords',
            name='measurementMethod',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='biodiversityrecords',
            name='measurementRemarks',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='biodiversityrecords',
            name='measurementType',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='biodiversityrecords',
            name='measurementUnit',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='biodiversityrecords',
            name='measurementValue',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='biodiversityrecords',
            name='minimumDepthInMeters',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='biodiversityrecords',
            name='modified',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='biodiversityrecords',
            name='month',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='biodiversityrecords',
            name='nameAccordingTo',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='biodiversityrecords',
            name='namePublishedIn',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='biodiversityrecords',
            name='namePublishedInYear',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='biodiversityrecords',
            name='occurrenceRemarks',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='biodiversityrecords',
            name='occurrenceStatus',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='biodiversityrecords',
            name='organismQuantity',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='biodiversityrecords',
            name='organismQuantityType',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='biodiversityrecords',
            name='parentNameUsage',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='biodiversityrecords',
            name='parentNameUsageID',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='biodiversityrecords',
            name='recordNumber',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='biodiversityrecords',
            name='recordedBy',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='biodiversityrecords',
            name='reproductiveCondition',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='biodiversityrecords',
            name='rightsHolder',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='biodiversityrecords',
            name='sampleSizeUnit',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='biodiversityrecords',
            name='sampleSizeValue',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='biodiversityrecords',
            name='samplingEffort',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='biodiversityrecords',
            name='samplingProtocol',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='biodiversityrecords',
            name='scientificName',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='biodiversityrecords',
            name='scientificNameAuthorship',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='biodiversityrecords',
            name='scientificNameID',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='biodiversityrecords',
            name='sex',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='biodiversityrecords',
            name='taxonRank',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='biodiversityrecords',
            name='taxonRemarks',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='biodiversityrecords',
            name='taxonomicStatus',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='biodiversityrecords',
            name='verbatimDepth',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='biodiversityrecords',
            name='year',
            field=models.IntegerField(null=True),
        ),
    ]
