# Generated by Django 3.1.3 on 2020-11-10 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0010_auto_20201110_1837'),
    ]

    operations = [
        migrations.RenameField(
            model_name='speciesrecords',
            old_name='acceptedSpeciesName',
            new_name='Class',
        ),
        migrations.RenameField(
            model_name='speciesrecords',
            old_name='speciesName',
            new_name='Family',
        ),
        migrations.AddField(
            model_name='speciesrecords',
            name='Genus',
            field=models.CharField(default='NA', max_length=255),
        ),
        migrations.AddField(
            model_name='speciesrecords',
            name='Kingdom',
            field=models.CharField(default='NA', max_length=255),
        ),
        migrations.AddField(
            model_name='speciesrecords',
            name='Order',
            field=models.CharField(default='NA', max_length=255),
        ),
        migrations.AddField(
            model_name='speciesrecords',
            name='Phylum',
            field=models.CharField(default='NA', max_length=255),
        ),
        migrations.AddField(
            model_name='speciesrecords',
            name='acceptedNameUsage',
            field=models.CharField(default='NA', max_length=255),
        ),
        migrations.AddField(
            model_name='speciesrecords',
            name='acceptedNameUsageID',
            field=models.CharField(default='NA', max_length=255),
        ),
        migrations.AddField(
            model_name='speciesrecords',
            name='commonNamePT',
            field=models.CharField(default='NA', max_length=255),
        ),
        migrations.AddField(
            model_name='speciesrecords',
            name='conservationIUCNEurope',
            field=models.CharField(default='NA', max_length=255),
        ),
        migrations.AddField(
            model_name='speciesrecords',
            name='conservationIUCNGlobal',
            field=models.CharField(default='NA', max_length=255),
        ),
        migrations.AddField(
            model_name='speciesrecords',
            name='conservationN2000',
            field=models.CharField(default='NA', max_length=255),
        ),
        migrations.AddField(
            model_name='speciesrecords',
            name='conservationN2000Code',
            field=models.CharField(default='NA', max_length=255),
        ),
        migrations.AddField(
            model_name='speciesrecords',
            name='conservationOther',
            field=models.CharField(default='NA', max_length=255),
        ),
        migrations.AddField(
            model_name='speciesrecords',
            name='conservationRedBookPt',
            field=models.CharField(default='NA', max_length=255),
        ),
        migrations.AddField(
            model_name='speciesrecords',
            name='namePublishedIn',
            field=models.CharField(default='NA', max_length=255),
        ),
        migrations.AddField(
            model_name='speciesrecords',
            name='namePublishedInYear',
            field=models.CharField(default='NA', max_length=255),
        ),
        migrations.AddField(
            model_name='speciesrecords',
            name='originalNameUsageID',
            field=models.CharField(default='NA', max_length=255),
        ),
        migrations.AddField(
            model_name='speciesrecords',
            name='parentNameUsageID',
            field=models.CharField(default='NA', max_length=255),
        ),
        migrations.AddField(
            model_name='speciesrecords',
            name='scientificName',
            field=models.CharField(default='NA', max_length=255),
        ),
        migrations.AddField(
            model_name='speciesrecords',
            name='scientificNameAuthorship',
            field=models.CharField(default='NA', max_length=255),
        ),
        migrations.AddField(
            model_name='speciesrecords',
            name='taxonRank',
            field=models.CharField(default='NA', max_length=255),
        ),
        migrations.AddField(
            model_name='speciesrecords',
            name='taxonRemarks',
            field=models.CharField(default='NA', max_length=255),
        ),
        migrations.AddField(
            model_name='speciesrecords',
            name='taxonomicStatus',
            field=models.CharField(default='NA', max_length=255),
        ),
    ]
