# Generated by Django 3.1.3 on 2020-11-10 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0013_auto_20201110_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='biodiversityrecords',
            name='occurrenceID',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
