# Generated by Django 3.1.3 on 2020-11-11 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0014_biodiversityrecords_occurrenceid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='speciesrecords',
            name='Class',
        ),
        migrations.RemoveField(
            model_name='speciesrecords',
            name='Family',
        ),
        migrations.RemoveField(
            model_name='speciesrecords',
            name='Genus',
        ),
        migrations.RemoveField(
            model_name='speciesrecords',
            name='Kingdom',
        ),
        migrations.RemoveField(
            model_name='speciesrecords',
            name='Order',
        ),
        migrations.RemoveField(
            model_name='speciesrecords',
            name='Phylum',
        ),
        migrations.RemoveField(
            model_name='speciesrecords',
            name='acceptedNameUsage',
        ),
        migrations.RemoveField(
            model_name='speciesrecords',
            name='acceptedNameUsageID',
        ),
        migrations.RemoveField(
            model_name='speciesrecords',
            name='commonNamePT',
        ),
        migrations.RemoveField(
            model_name='speciesrecords',
            name='conservationIUCNEurope',
        ),
        migrations.RemoveField(
            model_name='speciesrecords',
            name='conservationIUCNGlobal',
        ),
        migrations.RemoveField(
            model_name='speciesrecords',
            name='conservationN2000',
        ),
        migrations.RemoveField(
            model_name='speciesrecords',
            name='conservationN2000Code',
        ),
        migrations.RemoveField(
            model_name='speciesrecords',
            name='conservationOther',
        ),
        migrations.RemoveField(
            model_name='speciesrecords',
            name='conservationRedBookPt',
        ),
        migrations.RemoveField(
            model_name='speciesrecords',
            name='namePublishedIn',
        ),
        migrations.RemoveField(
            model_name='speciesrecords',
            name='namePublishedInYear',
        ),
        migrations.RemoveField(
            model_name='speciesrecords',
            name='originalNameUsageID',
        ),
        migrations.RemoveField(
            model_name='speciesrecords',
            name='parentNameUsageID',
        ),
        migrations.RemoveField(
            model_name='speciesrecords',
            name='scientificNameAuthorship',
        ),
        migrations.RemoveField(
            model_name='speciesrecords',
            name='taxonRank',
        ),
        migrations.RemoveField(
            model_name='speciesrecords',
            name='taxonRemarks',
        ),
        migrations.RemoveField(
            model_name='speciesrecords',
            name='taxonomicStatus',
        ),
    ]
