# Generated by Django 3.1.3 on 2021-01-27 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0015_auto_20201111_0927'),
    ]

    operations = [
        migrations.AddField(
            model_name='speciesrecords',
            name='conservationIUCNEurope',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='speciesrecords',
            name='conservationIUCNGlobal',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='speciesrecords',
            name='conservationN2000',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='speciesrecords',
            name='conservationN2000Code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='speciesrecords',
            name='conservationRedBookPt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='speciesrecords',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='speciesrecords',
            name='descriptionSource',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='speciesrecords',
            name='mainMediaFile',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
